name=homee-api-esp32
version=0.4.0
author=Daniel Knoop, Andreas
maintainer=
sentence=Virtueller homee für ESP32 und ESP8266
paragraph=Async TCP Library for ESP32
category=Other
url=https://github.com/Oxi75/homee-api-esp32
architectures=*