; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = *_env.ini

[common_env_data]
lib_deps = 
    ; Aktualisiert auf v7 (Achtung: Code-Anpassungen nötig!)
    bblanchon/ArduinoJson @ 7.3.1
    ; Die angeforderte WebServer Version (kompatibel mit ESP32 & ESP8266)
    ESP32Async/ESPAsyncWebServer @ 3.7.2
    ESP32Async/AsyncTCP @ 3.3.6

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps = 
    ${common_env_data.lib_deps}
    ; Spezifische TCP Lib für ESP32
    ESP32Async/AsyncTCP @ 3.3.6
build_flags = 
    ${wlancredentials.build_flags_wlan}
    -DEXAMPLE_BUILD
    -DDEBUG_VIRTUAL_HOMEE

[env:nodemcuv2]
platform = espressif8266
board = esp01_1m
framework = arduino
monitor_speed = 115200
lib_deps = 
    ${common_env_data.lib_deps}
    ; Das Gegenstück zur AsyncTCP für den ESP8266 (aus gleichem Hause)
    ESP32Async/ESPAsyncTCP
    ; UDP Lib weiterhin spezifisch für ESP8266 belassen
    https://github.com/DanielKnoop/ESPAsyncUDP.git
build_flags = 
    ${wlancredentials.build_flags_wlan}
    -DEXAMPLE_BUILD
    -DDEBUG_VIRTUAL_HOMEE